package visionriswebCMS.model.bo;
// Generated 21 f�vr. 2015 18:00:47 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Installs generated by hbm2java
 */
@Entity
@Table(name = "installs", schema = "dbo", catalog = "visionriswebCMS"
)
public class Installs implements java.io.Serializable {

    private int installId;
    private Date installDate;
    private String clientName;
    private Double serverRam;
    private Double serverHd;
    private String binTechFullname;
    private String localTechFullname;
    private String localTechContact;
    private String mainRadiologFullname;
    private String mainRadiologContact;
    private String installWantedFuncs;
    private String installCity;
    private String installCountry;
    private String installActiveVersion;
    private String installFirstVersion;
    private String activeProblems;
    private String recomSolutions;
    private String operStatus;
    private Double serverBandwidth;
    private String installUrl;
    private Boolean comTaken;

    public Installs() {
    }

    public Installs(int installId, Date installDate, String clientName) {
        this.installId = installId;
        this.installDate = installDate;
        this.clientName = clientName;
    }

    public Installs(int installId, Date installDate, String clientName, Double serverRam, Double serverHd, String binTechFullname, String localTechFullname, String localTechContact, String mainRadiologFullname, String mainRadiologContact, String installWantedFuncs, String installCity, String installCountry, String installActiveVersion, String installFirstVersion, String activeProblems, String recomSolutions, String operStatus, Double serverBandwidth, String installUrl, Boolean comTaken) {
        this.installId = installId;
        this.installDate = installDate;
        this.clientName = clientName;
        this.serverRam = serverRam;
        this.serverHd = serverHd;
        this.binTechFullname = binTechFullname;
        this.localTechFullname = localTechFullname;
        this.localTechContact = localTechContact;
        this.mainRadiologFullname = mainRadiologFullname;
        this.mainRadiologContact = mainRadiologContact;
        this.installWantedFuncs = installWantedFuncs;
        this.installCity = installCity;
        this.installCountry = installCountry;
        this.installActiveVersion = installActiveVersion;
        this.installFirstVersion = installFirstVersion;
        this.activeProblems = activeProblems;
        this.recomSolutions = recomSolutions;
        this.operStatus = operStatus;
        this.serverBandwidth = serverBandwidth;
        this.installUrl = installUrl;
        this.comTaken = comTaken;
    }

    @Id

    @Column(name = "install_id", unique = true, nullable = false)
    public int getInstallId() {
        return this.installId;
    }

    public void setInstallId(int installId) {
        this.installId = installId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "install_date", nullable = false, length = 23)
    public Date getInstallDate() {
        return this.installDate;
    }

    public void setInstallDate(Date installDate) {
        this.installDate = installDate;
    }

    @Column(name = "client_name", nullable = false, length = 200)
    public String getClientName() {
        return this.clientName;
    }

    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    @Column(name = "server_ram", precision = 53, scale = 0)
    public Double getServerRam() {
        return this.serverRam;
    }

    public void setServerRam(Double serverRam) {
        this.serverRam = serverRam;
    }

    @Column(name = "server_hd", precision = 53, scale = 0)
    public Double getServerHd() {
        return this.serverHd;
    }

    public void setServerHd(Double serverHd) {
        this.serverHd = serverHd;
    }

    @Column(name = "bin_tech_fullname", length = 200)
    public String getBinTechFullname() {
        return this.binTechFullname;
    }

    public void setBinTechFullname(String binTechFullname) {
        this.binTechFullname = binTechFullname;
    }

    @Column(name = "local_tech_fullname", length = 200)
    public String getLocalTechFullname() {
        return this.localTechFullname;
    }

    public void setLocalTechFullname(String localTechFullname) {
        this.localTechFullname = localTechFullname;
    }

    @Column(name = "local_tech_contact", length = 200)
    public String getLocalTechContact() {
        return this.localTechContact;
    }

    public void setLocalTechContact(String localTechContact) {
        this.localTechContact = localTechContact;
    }

    @Column(name = "main_radiolog_fullname", length = 200)
    public String getMainRadiologFullname() {
        return this.mainRadiologFullname;
    }

    public void setMainRadiologFullname(String mainRadiologFullname) {
        this.mainRadiologFullname = mainRadiologFullname;
    }

    @Column(name = "main_radiolog_contact", length = 200)
    public String getMainRadiologContact() {
        return this.mainRadiologContact;
    }

    public void setMainRadiologContact(String mainRadiologContact) {
        this.mainRadiologContact = mainRadiologContact;
    }

    @Column(name = "install_wanted_funcs", length = 200)
    public String getInstallWantedFuncs() {
        return this.installWantedFuncs;
    }

    public void setInstallWantedFuncs(String installWantedFuncs) {
        this.installWantedFuncs = installWantedFuncs;
    }

    @Column(name = "install_city")
    public String getInstallCity() {
        return this.installCity;
    }

    public void setInstallCity(String installCity) {
        this.installCity = installCity;
    }

    @Column(name = "install_country", length = 200)
    public String getInstallCountry() {
        return this.installCountry;
    }

    public void setInstallCountry(String installCountry) {
        this.installCountry = installCountry;
    }

    @Column(name = "install_active_version", length = 200)
    public String getInstallActiveVersion() {
        return this.installActiveVersion;
    }

    public void setInstallActiveVersion(String installActiveVersion) {
        this.installActiveVersion = installActiveVersion;
    }

    @Column(name = "install_first_version", length = 200)
    public String getInstallFirstVersion() {
        return this.installFirstVersion;
    }

    public void setInstallFirstVersion(String installFirstVersion) {
        this.installFirstVersion = installFirstVersion;
    }

    @Column(name = "active_problems", nullable = true)
    public String getActiveProblems() {
        return this.activeProblems;
    }

    public void setActiveProblems(String activeProblems) {
        this.activeProblems = activeProblems;
    }

    @Column(name = "recom_solutions")
    public String getRecomSolutions() {
        return this.recomSolutions;
    }

    public void setRecomSolutions(String recomSolutions) {
        this.recomSolutions = recomSolutions;
    }

    @Column(name = "oper_status", length = 200)
    public String getOperStatus() {
        String result = null;
        System.out.println(operStatus);
        switch (operStatus) {
            case "0":
                result = "WORKING AND UPDATED";
                break;
            case "1":
                result = "WORKING NEEDS UPDATE";
                break;
            case "2":
                result = "INSTALLED";
                break;
            case "3":
                result = "HAS PROBLEMS";
                break;
            case "4":
                result = "SERVER STOPPED";
                break;

        }

        return result;
    }

    public void setOperStatus(String operStatus) {
        this.operStatus = operStatus;
    }

    @Column(name = "server_bandwidth", precision = 53, scale = 0)
    public Double getServerBandwidth() {
        return this.serverBandwidth;
    }

    public void setServerBandwidth(Double serverBandwidth) {
        this.serverBandwidth = serverBandwidth;
    }

    @Column(name = "install_url", length = 1000)
    public String getInstallUrl() {
        return this.installUrl;
    }

    public void setInstallUrl(String installUrl) {
        this.installUrl = installUrl;
    }

    @Column(name = "com_taken", precision = 1, scale = 0)
    public Boolean getComTaken() {
        return this.comTaken;
    }

    public void setComTaken(Boolean comTaken) {
        this.comTaken = comTaken;
    }

}
